practice/Python/Django/tutorial_student/pjt/sProject/students/urls.py
from django.urls import path
from . import views

# 이곳은 모든 url을 적어서 맵핑하는 파일
# 하지만 모든 url을 이곳에 적는 것 보다는
# 각 어플리케이션마다 url을 관리하는 것이 효율적이다

# 찾기 쉽게 도와주는 변수
app_name = 'students'

# url 맵핑
urlpatterns = [
    # reg로 시작하는 url이 들어오면, 이 메소드를 실행하라,
    # name은 views에서 사용함
    path('reg/', views.regStudent, name='reg'),
    path('regCon/', views.regConStudent, name='regCon'),
    path('all/', views.readStudentAll, name='stuAll'),
    path('<str:name>/det/', views.detStudent, name='stuDet'),
    path('<str:name>/mod/', views.ModStudent, name='stuMod'),
    path('modcon/', views.ModConStudent, name='modCon'),
    path('<str:name>/del', views.delStudent, name='stuDel'),
    # <str:name>은 vies.delStudent를 실행할 때 넘겨주는 인자 name이 왼다


]

practice/Python/Django/tutorial_student/pjt/sProject/studentsProject/urls.py
from django.contrib import admin
from django.urls import path,include

# 이곳은 모든 url을 적어서 맵핑하는 파일
# 하지만 모든 url을 이곳에 적는 것 보다는
# 각 어플리케이션마다 url을 관리하는 것이 효율적이다
urlpatterns = [
    path('admin/', admin.site.urls),# 프로젝트 전체 관리하는 url

    # students로 시작하는 url이 들어오면 studnet.urls파일을 include하라는 메소드
    path('students/', include('students.urls')),

]

practice/Python/Django/tutorial_student/pjt/sProject/students/models.py
# Create your models here.
from django.db import models

# 클래스를 만듦으로써 DB테이블을 생성한다
# 테이블명이 Student인 테이블을 생성하는 작업 -> 즉, migrate해야함
# 내장클래스인 models.Model를 상속받아야함
class Student(models.Model):
    s_name = models.CharField(max_length=100)
    s_major = models.CharField(max_length=100)
    s_age = models.IntegerField(default=0)
    s_grade = models.IntegerField(default=0)
    s_gender = models.CharField(max_length=30)


    # shell에서 작업할 때 return되는 값을 지정하는 것
    # sohye 이런 값이 출력되어서 구분한다
    def __str__(self):
        return self.s_name

practice/Python/Django/tutorial_student/pjt/sProject/students/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from students.models import Student

def regStudent(request):
    # 위의 함수를 호출하면 아래의 *.html로 이동하게 만들어줌
    return render(request, 'students/registerStudent.html')


def regConStudent(request):

    # POST방식으로 들어오므로 POST로 씀

    name = request.POST['name']
    major = request.POST['major']
    age = request.POST['age']
    grade = request.POST['grade']
    gender = request.POST['gender']

    # 쿼리스트링qs에 request를 통해 들어온 데이터를 집어넣는다
    # Student객체(사실상 DB테이블을 의미)를 생성해서 사용한다
    qs = Student(s_name = name, s_major = major, s_age = age, s_grade = grade, s_gender = gender)

    # 반드시 save를 해야 DB에 저장된다
    qs.save()

    # 위의 작업을 마친 후 stuall 템플릿을 띄우라는 redirection
    # stuAll이 urls의 name을 의미함.
    return HttpResponseRedirect(reverse('students:stuAll'))

# 모든 학생 조회하는 메소드
def readStudentAll(request):

    # objects.all이 모든 데이터 조회하는 것
    qs = Student.objects.all()
    context =  { 'student_list': qs } # dict로 넘겨줌

    return render(request, 'students/readStudents.html', context)

# 학생 세부정보
def detStudent(request, name):
    qs = Student.objects.get(s_name = name)
    context = {'student_info' : qs}

    return render(request, 'students/detailStudent.html', context)

# 학생 정보 수정하는 페이지
def ModStudent(request, name):
    qs = Student.objects.get(s_name = name) # s_name이 name과 같은 데이터row를 가져오겠다
    context = {'student_info': qs}

    return render(request, 'students/modifyStudent.html', context)

# 수정한 학생정보를 DB에 업데이트 시키는 메소드
def ModConStudent(request):
    # 수정한 정보가 담겨있는 request
    name = request.POST['name']
    major = request.POST['major']
    age = request.POST['age']
    grade = request.POST['grade']
    gender = request.POST['gender']

    # 학생 1건 정보 조회
    qs = Student.objects.get(s_name = name)

    # 수정한 정보로 교체
    qs.s_name = name
    qs.s_major = major
    qs.s_age = age
    qs.s_grade = grade
    qs.s_gender = gender

    # save를 해야 DB에 업데이트 됨
    qs.save()

    # 위의 작업을 마친 후 stuall 템플릿을 띄우라는 redirection
    return HttpResponseRedirect(reverse('students:stuAll'))


# 학생 삭제
def delStudent(request, name):

    qs = Student.objects.get(s_name = name)
    qs.delete()

    # 위의 작업을 마친 후 stuall 템플릿을 띄우라는 redirection
    return HttpResponseRedirect(reverse('students:stuAll'))

practice/Python/Django/tutorial_student/pjt/sProject/students/templates/students/detailStudent.html
<!DOCTYPE html>

<html>
    <head>
       <meta http-equiv="content-type" content="text/html" charset=UTF-8>
        <title>title</title>
    </head>
    <body>
        <p>Detail Student</p>

        {% if student_info %}
            name : {{student_info.s_name}} </br>
            major : {{student_info.s_major}} </br>
            age : {{student_info.s_age}} </br>
            grade : {{student_info.s_grade}} </br>
            gender : {{student_info.s_gender}} </br>

        {% else %}
            <p> Student: 0 </p>
        {% endif %}


        </br>
        <!-- url'students:stuMod'을 가져오라는 의미이고, 뒤에는  student_info.s_name을 인자로 넘겨준다는 의미-->
        <!-- 이렇게 인자로 넘겨주면 urls.py에서 <str:name>을 사용한다-->
        <a href="{% url 'students:stuMod' student_info.s_name %}">수정</a>
        <a href="{% url 'students:stuDel' student_info.s_name %}">삭제</a>
        <a href="{% url 'students:stuAll' %}">학생리스트</a>
        <a href="{% url 'students:reg' %}">신규학생등록</a>


    </body>

</html>

practice/Python/Django/tutorial_student/pjt/sProject/students/templates/students/modifyStudent.html
<!DOCTYPE html>

<html>
    <head>
       <meta http-equiv="content-type" content="text/html"; charset=UTF-8>
        <title>title</title>
    </head>
    <body>
        <p>Modify Student</p>

        {% if student_info %}

            <form action="{% url 'students:modCon' %}" method="post">
                {% csrf_token %}
                name : {{student_info.s_name}}
                <input type="hidden" name="name" value="{{student_info.s_name}}"></br>  <!--    이름은 수정되면 안되므로 type을 hidden으로 바꿈            -->
                major : <input type="text" name="major" value="{{student_info.s_major}}"></br>
                age : <input type="text" name="age" value="{{student_info.s_age}}"></br>
                grade : <input type="text" name="grade" value="{{student_info.s_grade}}"></br>
                gender : <input type="text" name="gender" value="{{student_info.s_gender}}"></br>
                <input type="submit" name="Register"></br>
            </form>


        {% else %}
            <p> student : 0</p>
        {% endif%}


    </body>
</html>

practice/Python/Django/tutorial_student/pjt/sProject/students/templates/students/readStudents.html
<!DOCTYPE html>

<html>
    <head>
       <meta http-equiv="content-type" content="text/html" charset=UTF-8>
        <title>title</title>
    </head>
    <body>
        <p>Read Student</p>

        {% if student_list %}
        <ol>
            {% for s in student_list %}
            <li>
                <a href="{% url 'students:stuDet' s.s_name %}  ">{{s.s_name}}</a>
                <a href="{% url 'students:stuMod' s.s_name %}">수정</a>
                <a href="{% url 'students:stuDel' s.s_name %}">삭제</a>
            </li>
            {% endfor%}
        </ol>
        {% else %}
            <p> Student : 0</p>
        {% endif %}

        </br>

        <a href="{% url 'students:reg' %}">신규학생등록</a>

    </body>

</html>

practice/Python/Django/tutorial_student/pjt/sProject/students/templates/students/registerStudent.html
<!DOCTYPE html>

<html>
    <head>
       <meta http-equiv="content-type" content="text/html"; charset=UTF-8>
        <title>title</title>
    </head>
    <body>
        <p>Register Student</p>
        <form action="{% url 'students:regCon' %}" method="post">
        {% csrf_token %}
            name : <input type="text" name="name"></br>
            major : <input type="text" name="major"></br>
            age : <input type="text" name="age"></br>
            grade : <input type="text" name="grade"></br>
            gender : <input type="text" name="gender"></br>
            <input type="submit" name="Register"></br>
        </form>
    </body>
</html>